[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow = "uRudht3CDqxsPojNmAC9beKQpiwjeyULPkyGKMkuTqm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[toolchain]
anchor_version = "0.31.0"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"